// Generated by gencpp from file mrta/AuctionRequest.msg
// DO NOT EDIT!


#ifndef MRTA_MESSAGE_AUCTIONREQUEST_H
#define MRTA_MESSAGE_AUCTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mrta/Task.h>

namespace mrta
{
template <class ContainerAllocator>
struct AuctionRequest_
{
  typedef AuctionRequest_<ContainerAllocator> Type;

  AuctionRequest_()
    : id(0)
    , tasks()
    , PC()  {
    }
  AuctionRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , tasks(_alloc)
    , PC(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::vector< ::mrta::Task_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mrta::Task_<ContainerAllocator> >::other >  _tasks_type;
  _tasks_type tasks;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _PC_type;
  _PC_type PC;





  typedef boost::shared_ptr< ::mrta::AuctionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrta::AuctionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AuctionRequest_

typedef ::mrta::AuctionRequest_<std::allocator<void> > AuctionRequest;

typedef boost::shared_ptr< ::mrta::AuctionRequest > AuctionRequestPtr;
typedef boost::shared_ptr< ::mrta::AuctionRequest const> AuctionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrta::AuctionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrta::AuctionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrta

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrta': ['/home/kimwang/Desktop/MRTA-devel/catkin_ws/src/mrta/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrta::AuctionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrta::AuctionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrta::AuctionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrta::AuctionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrta::AuctionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrta::AuctionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrta::AuctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1a8db4f2cc429740600e9b48c19cbd1";
  }

  static const char* value(const ::mrta::AuctionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1a8db4f2cc42974ULL;
  static const uint64_t static_value2 = 0x0600e9b48c19cbd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrta::AuctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrta/AuctionRequest";
  }

  static const char* value(const ::mrta::AuctionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrta::AuctionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
Task[] tasks\n\
int32[] PC\n\
================================================================================\n\
MSG: mrta/Task\n\
int32 id\n\
int32 start_time\n\
int32 finish_time\n\
int32 est\n\
int32 lst\n\
int32 eft\n\
int32 lft\n\
int32 duration\n\
int32[2] location\n\
";
  }

  static const char* value(const ::mrta::AuctionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrta::AuctionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.tasks);
      stream.next(m.PC);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuctionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrta::AuctionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrta::AuctionRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "tasks[]" << std::endl;
    for (size_t i = 0; i < v.tasks.size(); ++i)
    {
      s << indent << "  tasks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mrta::Task_<ContainerAllocator> >::stream(s, indent + "    ", v.tasks[i]);
    }
    s << indent << "PC[]" << std::endl;
    for (size_t i = 0; i < v.PC.size(); ++i)
    {
      s << indent << "  PC[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.PC[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRTA_MESSAGE_AUCTIONREQUEST_H
