// Generated by gencpp from file mrta/AuctionAck.msg
// DO NOT EDIT!


#ifndef MRTA_MESSAGE_AUCTIONACK_H
#define MRTA_MESSAGE_AUCTIONACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrta
{
template <class ContainerAllocator>
struct AuctionAck_
{
  typedef AuctionAck_<ContainerAllocator> Type;

  AuctionAck_()
    : auc_id(0)
    , robot_id(0)  {
    }
  AuctionAck_(const ContainerAllocator& _alloc)
    : auc_id(0)
    , robot_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _auc_id_type;
  _auc_id_type auc_id;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::mrta::AuctionAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrta::AuctionAck_<ContainerAllocator> const> ConstPtr;

}; // struct AuctionAck_

typedef ::mrta::AuctionAck_<std::allocator<void> > AuctionAck;

typedef boost::shared_ptr< ::mrta::AuctionAck > AuctionAckPtr;
typedef boost::shared_ptr< ::mrta::AuctionAck const> AuctionAckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrta::AuctionAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrta::AuctionAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrta

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrta': ['/home/kimwang/Desktop/MRTA-devel/catkin_ws/src/mrta/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrta::AuctionAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrta::AuctionAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrta::AuctionAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrta::AuctionAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrta::AuctionAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrta::AuctionAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrta::AuctionAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "168a584f870d2ab3dda7180656bbecb2";
  }

  static const char* value(const ::mrta::AuctionAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x168a584f870d2ab3ULL;
  static const uint64_t static_value2 = 0xdda7180656bbecb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrta::AuctionAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrta/AuctionAck";
  }

  static const char* value(const ::mrta::AuctionAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrta::AuctionAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 auc_id\n\
int32 robot_id\n\
";
  }

  static const char* value(const ::mrta::AuctionAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrta::AuctionAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.auc_id);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuctionAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrta::AuctionAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrta::AuctionAck_<ContainerAllocator>& v)
  {
    s << indent << "auc_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.auc_id);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRTA_MESSAGE_AUCTIONACK_H
