// Generated by gencpp from file mrta/TerminateRobot.msg
// DO NOT EDIT!


#ifndef MRTA_MESSAGE_TERMINATEROBOT_H
#define MRTA_MESSAGE_TERMINATEROBOT_H

#include <ros/service_traits.h>


#include <mrta/TerminateRobotRequest.h>
#include <mrta/TerminateRobotResponse.h>


namespace mrta
{

struct TerminateRobot
{

typedef TerminateRobotRequest Request;
typedef TerminateRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TerminateRobot
} // namespace mrta


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mrta::TerminateRobot > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::mrta::TerminateRobot&) { return value(); }
};

template<>
struct DataType< ::mrta::TerminateRobot > {
  static const char* value()
  {
    return "mrta/TerminateRobot";
  }

  static const char* value(const ::mrta::TerminateRobot&) { return value(); }
};


// service_traits::MD5Sum< ::mrta::TerminateRobotRequest> should match 
// service_traits::MD5Sum< ::mrta::TerminateRobot > 
template<>
struct MD5Sum< ::mrta::TerminateRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mrta::TerminateRobot >::value();
  }
  static const char* value(const ::mrta::TerminateRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrta::TerminateRobotRequest> should match 
// service_traits::DataType< ::mrta::TerminateRobot > 
template<>
struct DataType< ::mrta::TerminateRobotRequest>
{
  static const char* value()
  {
    return DataType< ::mrta::TerminateRobot >::value();
  }
  static const char* value(const ::mrta::TerminateRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mrta::TerminateRobotResponse> should match 
// service_traits::MD5Sum< ::mrta::TerminateRobot > 
template<>
struct MD5Sum< ::mrta::TerminateRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mrta::TerminateRobot >::value();
  }
  static const char* value(const ::mrta::TerminateRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mrta::TerminateRobotResponse> should match 
// service_traits::DataType< ::mrta::TerminateRobot > 
template<>
struct DataType< ::mrta::TerminateRobotResponse>
{
  static const char* value()
  {
    return DataType< ::mrta::TerminateRobot >::value();
  }
  static const char* value(const ::mrta::TerminateRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MRTA_MESSAGE_TERMINATEROBOT_H
