# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mrta/Task.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Task(genpy.Message):
  _md5sum = "d86f5da30db4f9950e8526203585575b"
  _type = "mrta/Task"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id
int32 start_time
int32 finish_time
int32 est
int32 lst
int32 eft
int32 lft
int32 duration
int32[2] location"""
  __slots__ = ['id','start_time','finish_time','est','lst','eft','lft','duration','location']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32','int32[2]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,start_time,finish_time,est,lst,eft,lft,duration,location

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Task, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.start_time is None:
        self.start_time = 0
      if self.finish_time is None:
        self.finish_time = 0
      if self.est is None:
        self.est = 0
      if self.lst is None:
        self.lst = 0
      if self.eft is None:
        self.eft = 0
      if self.lft is None:
        self.lft = 0
      if self.duration is None:
        self.duration = 0
      if self.location is None:
        self.location = [0] * 2
    else:
      self.id = 0
      self.start_time = 0
      self.finish_time = 0
      self.est = 0
      self.lst = 0
      self.eft = 0
      self.lft = 0
      self.duration = 0
      self.location = [0] * 2

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.id, _x.start_time, _x.finish_time, _x.est, _x.lst, _x.eft, _x.lft, _x.duration))
      buff.write(_get_struct_2i().pack(*self.location))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.start_time, _x.finish_time, _x.est, _x.lst, _x.eft, _x.lft, _x.duration,) = _get_struct_8i().unpack(str[start:end])
      start = end
      end += 8
      self.location = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.id, _x.start_time, _x.finish_time, _x.est, _x.lst, _x.eft, _x.lft, _x.duration))
      buff.write(self.location.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.id, _x.start_time, _x.finish_time, _x.est, _x.lst, _x.eft, _x.lft, _x.duration,) = _get_struct_8i().unpack(str[start:end])
      start = end
      end += 8
      self.location = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=2)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
